name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download and Install Node.js
      run: |
        Invoke-WebRequest -Uri https://nodejs.org/dist/v16.17.0/node-v16.17.0-x64.msi -OutFile nodejs.msi
        Start-Process msiexec.exe -ArgumentList '/i', 'nodejs.msi', '/quiet', '/norestart' -Wait
        Remove-Item -Force nodejs.msi
    
    - name: Install Localtunnel
      run: npm install -g localtunnel

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Local User Credentials
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start Localtunnel
      run: |
        $lt_process = Start-Process lt --port 3389 --subdomain allahutealacellehu -PassThru
        Start-Sleep -Seconds 5  # Give it a moment to set up

    - name: Get Tunnel Password
      run: |
        # Use curl to get the tunnel password from the public IP
        $password = curl https://loca.lt/mytunnelpassword
        Write-Output "Tunnel Password: $password"
    
    - name: Wait for Localtunnel to be available
      run: Start-Sleep -Seconds 10
